# Generated by Django 4.1.7 on 2023-06-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='media/images/default.png', upload_to='media/images/'),
        ),
    ]
