# Generated by Django 4.1.7 on 2023-06-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_status_user_bio_user_gender_user_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='static/images/default.png', upload_to='static/images/'),
        ),
    ]
