# Generated by Django 4.1.7 on 2023-03-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0006_alter_profile_location_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True),
        ),
    ]
